export type Locale = 'th' | 'en'

export const copy = {
  th: {
    nav: {
      home: 'หน้าแรก',
      tours: 'ทัวร์',
      private: 'ทัวร์ส่วนตัว',
      fleet: 'เรือเจ็ตสกี',
      gallery: 'แกลเลอรี',
      faq: 'คำถามที่พบบ่อย',
      contact: 'ติดต่อ',
      book: 'จองเลย',
    },
    hero: {
      eyebrow: 'JET SKI TOURS PHUKET',
      title: 'สำรวจภูเก็ต\nขับเล่นมหาสมุทร',
      body: 'ทัวร์เจ็ตสกีพร้อมไกด์มืออาชีพ พาเที่ยวเกาะสวย น้ำใส และมุมถ่ายรูปตลอดเส้นทาง',
      trust: ['ไกด์มืออาชีพ', 'ดูแลความปลอดภัย', 'รถรับ–ส่งฟรี'],
      script: 'More Than a Tour\nIT’S A LIFESTYLE',
      bookTour: 'ทัวร์',
      bookDate: 'วันที่',
      bookGuests: 'จำนวนผู้ร่วม',
      check: 'เช็กที่ว่าง',
      tourOptions: ['10 เกาะ · รอบเช้า', '10 เกาะ · รอบบ่าย', 'ทัวร์ส่วนตัว'],
      guestOptions: ['1 ท่าน', '2 ท่าน'],
    },
    tours: {
      eyebrow: 'OUR TOURS',
      title: 'เลือกการผจญภัยของคุณ',
      sub: 'ทัวร์เจ็ตสกี Sea-Doo GTX PRO 130 — 4 ชั่วโมง เที่ยว 10 เกาะ',
      items: [
        {
          title: '10 เกาะ · รอบเช้า',
          desc: 'ออกทะเลช่วงเช้า สดชื่น วิวสวย เหมาะกับคนชอบแสงสวยถ่ายรูป',
          time: '4 ชม.',
          guests: 'สูงสุด 2 ท่าน',
          price: '฿7,500',
          features: [
            'Sea-Doo GTX PRO 130',
            'ไกด์นำทางตลอดทริป',
            'แวะจุดถ่ายรูปและพัก',
            'อาหารระหว่างทริป',
            'รถรับ–ส่งฟรีในภูเก็ต',
          ],
          cta: 'ดูรายละเอียดทัวร์',
          popular: false,
        },
        {
          title: '10 เกาะ · รอบบ่าย',
          desc: 'เส้นทางยอดนิยม 4 ชั่วโมง 10 เกาะ พร้อมทีมดูแลครบทุกช่วง',
          time: '4 ชม.',
          guests: 'สูงสุด 2 ท่าน',
          price: '฿7,500',
          features: [
            'Sea-Doo GTX PRO 130',
            'ไกด์มืออาชีพ',
            'ชมวิวเกาะและธรรมชาติ',
            'แวะพักและถ่ายภาพ',
            'ดูแลตั้งแต่ถึงจนจบทริป',
          ],
          cta: 'ดูรายละเอียดทัวร์',
          popular: true,
        },
        {
          title: 'ทัวร์ส่วนตัว',
          desc: 'จัดรอบส่วนตัวสำหรับคู่รักหรือกลุ่มเล็ก ที่ต้องการความเป็นส่วนตัวมากขึ้น',
          time: '4 ชม.',
          guests: 'สูงสุด 2 ท่าน/คัน',
          price: 'สอบถาม',
          features: [
            'เลือกเวลาได้ยืดหยุ่น',
            'ไกด์ดูแลใกล้ชิด',
            'เหมาะกับมือใหม่',
            'ถ่ายภาพเก็บโมเมนต์',
            'รถรับ–ส่งฟรี',
          ],
          cta: 'วางแผนทัวร์ส่วนตัว',
          popular: false,
        },
      ],
    },
    why: {
      eyebrow: 'WHY RIDE WITH US',
      title: 'ทำไมต้องขับกับเรา',
      sub: 'ออกแบบทริปให้สนุก ปลอดภัย และน่าจดจำตั้งแต่ก้าวแรก',
      items: [
        {
          title: 'เจ็ตสกีรุ่นใหม่',
          body: 'Sea-Doo GTX PRO 130 นั่งสบาย ขับมั่นใจตลอดทริป',
        },
        {
          title: 'ไกด์มีใบอนุญาต',
          body: 'ทีมมืออาชีพรอบรู้เส้นทางและดูแลความปลอดภัย',
        },
        {
          title: 'ความปลอดภัย',
          body: 'มีเสื้อชูชีพ คำแนะนำก่อนออก และดูแลตลอดเส้นทาง',
        },
        {
          title: 'รถรับ–ส่งโรงแรม',
          body: 'รับ–ส่งฟรีภายในจังหวัดภูเก็ตไป–กลับจุดเริ่มทัวร์',
        },
      ],
    },
    video: {
      title: 'Island Hopping Like Never Before',
      body: 'ขับเจ็ตสกีข้ามเกาะ สัมผัสทะเลภูเก็ตในมุมที่แตกต่าง',
      cta: 'ดูวิดีโอของเรา',
    },
    stops: {
      eyebrow: 'POPULAR STOPS',
      title: 'จุดแวะยอดนิยม',
      items: [
        {
          title: 'MONKEY ISLAND',
          desc: 'แวะถ่ายรูปกับธรรมชาติใกล้ชิด',
          image: 'images/gallery-1.jpg',
        },
        {
          title: 'LIMESTONE BAY',
          desc: 'อ่าวน้ำใสและหน้าผาเขียวชอุ่ม',
          image: 'images/package-3.jpg',
        },
        {
          title: 'OPEN SEA RUN',
          desc: 'ช่วงขับโล่ง สนุกและตื่นเต้น',
          image: 'images/hero.png',
        },
        {
          title: 'PHOTO STOP',
          desc: 'จุดพักและเก็บภาพความประทับใจ',
          image: 'images/gallery-2.jpg',
        },
      ],
    },
    pricing: {
      eyebrow: 'TOUR PRICING',
      title: 'ประสบการณ์ดีสำหรับทุกนักเดินทาง',
      sub: 'เลือกรอบเช้าหรือบ่าย หรือปรึกษาทัวร์ส่วนตัวได้ตามสไตล์ของคุณ',
      group: {
        title: 'ทัวร์มาตรฐาน',
        from: 'เริ่มต้น',
        price: '฿7,500',
        unit: 'ต่อคันเจ็ตสกี',
        features: [
          '4 ชั่วโมง · 10 เกาะ',
          'นั่งได้สูงสุด 2 ท่าน',
          'ไกด์นำทางตลอดทริป',
          'รถรับ–ส่งฟรีในภูเก็ต',
          'อาหารระหว่างทริป',
        ],
        cta: 'ดูทัวร์มาตรฐาน',
      },
      private: {
        title: 'ทัวร์ส่วนตัว',
        from: 'เริ่มต้น',
        price: 'สอบถามราคา',
        unit: 'จัดตามคำขอ',
        features: [
          'เวลาออกที่ยืดหยุ่นกว่า',
          'ประสบการณ์ส่วนตัวมากขึ้น',
          'เหมาะกับคู่รักและกลุ่มเล็ก',
          'ไกด์ดูแลใกล้ชิด',
          'รถรับ–ส่งฟรี',
        ],
        cta: 'วางแผนทัวร์ส่วนตัว',
      },
      note: 'ราคาปกติ ฿8,900 — จองตอนนี้เพียง ฿7,500 / คัน',
    },
    reviews: {
      eyebrow: 'CUSTOMER REVIEWS',
      title: 'ความไว้วางใจจากนักเดินทาง',
      rating: '4.9',
      based: 'จากรีวิวของนักท่องเที่ยวที่ร่วมทริปกับเรา',
      items: [
        {
          name: 'Anna K.',
          text: 'ทริปสนุกมาก ไกด์ดูแลดี วิวสวยตลอดทาง ประทับใจสุดๆ',
        },
        {
          name: 'James R.',
          text: 'ครั้งแรกที่ขับเจ็ตสกีก็มั่นใจได้ เพราะทีมสอนและดูแลตลอด',
        },
        {
          name: 'Mei L.',
          text: 'รถมารับถึงโรงแรม สะดวกมาก คุ้มค่ากับราคาโปร',
        },
      ],
    },
    gallery: {
      eyebrow: 'OUR GALLERY',
      title: 'โมเมนต์จริง การผจญภัยจริง',
    },
    schedule: {
      morning: 'รอบเช้า',
      morningTime: '09:00 – 13:00 น.',
      afternoon: 'รอบบ่าย',
      afternoonTime: '13:30 – 17:30 น.',
      note: 'เลือกรอบที่สะดวกได้ในขั้นตอนการจอง',
    },
    contactPage: {
      eyebrow: 'CONTACT',
      title: 'ช่องทางจองและสอบถาม',
      companyTh: 'บริษัท จี.ไอ.ซี. วิสต้า จำกัด',
      formTitle: 'ส่งข้อความถึงเรา',
      formDesc: 'กรอกข้อมูลแล้วกดส่ง ระบบจะเปิด WhatsApp ให้คุยต่อทันที',
      name: 'ชื่อ',
      message: 'ข้อความ',
      submit: 'ส่งทาง WhatsApp',
    },
    cta: {
      title: 'พร้อมสำหรับทริปภูเก็ตของคุณหรือยัง?',
      body: 'จองทัวร์เจ็ตสกี 4 ชั่วโมง 10 เกาะวันนี้ — ที่นั่งจำกัดในแต่ละรอบ',
      whatsapp: 'แชท WhatsApp',
      book: 'จองเลย',
      script: 'Good Vibes,\nBigger Adventures',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'คำถามที่พบบ่อย',
      items: [
        {
          q: 'ทัวร์กี่ชั่วโมง เที่ยวกี่เกาะ?',
          a: 'ประมาณ 4 ชั่วโมง เที่ยวชมได้มากถึง 10 เกาะ',
        },
        {
          q: 'รอบทัวร์มีกี่รอบ?',
          a: 'มี 2 รอบต่อวัน เช้า 09:00–13:00 และบ่าย 13:30–17:30',
        },
        {
          q: 'มีรถรับ–ส่งหรือไม่?',
          a: 'มีบริการรถรับ–ส่งฟรีภายในจังหวัดภูเก็ต',
        },
        {
          q: 'มือใหม่ขับได้ไหม?',
          a: 'ได้ ทีมงานพร้อมแนะนำและดูแลตลอดทริป',
        },
      ],
    },
    footer: {
      tagline: 'Jetski Travel & Sea Experience',
      quick: 'ลิงก์ด่วน',
      contact: 'ติดต่อเรา',
      follow: 'ติดตามเรา',
      explore: 'EXPLORE · RIDE · DISCOVER PHUKET',
      rights: '© 2026 G.I. SEA VISTA CO., LTD. สงวนลิขสิทธิ์',
      motto: 'Amazing People. Beautiful Places. Better Together.',
      company: 'G.I. SEA. VISTA CO., LTD.',
      address: '164 หมู่ที่ 6 ต.ป่าคลอก อ.ถลาง จ.ภูเก็ต 83110',
    },
  },
  en: {
    nav: {
      home: 'Home',
      tours: 'Tours',
      private: 'Private Tour',
      fleet: 'Fleet',
      gallery: 'Gallery',
      faq: 'FAQ',
      contact: 'Contact',
      book: 'BOOK NOW',
    },
    hero: {
      eyebrow: 'JET SKI TOURS PHUKET',
      title: 'EXPLORE PHUKET.\nRIDE THE OCEAN.',
      body: 'Guided jet ski tours across beautiful islands, hidden coves, and crystal-clear waters — with safety and fun the whole way.',
      trust: ['Professional Guides', 'Safety First', 'Free Hotel Transfer'],
      script: 'More Than a Tour\nIT’S A LIFESTYLE',
      bookTour: 'Tour',
      bookDate: 'Date',
      bookGuests: 'Guests',
      check: 'CHECK AVAILABILITY',
      tourOptions: ['10 Islands · Morning', '10 Islands · Afternoon', 'Private Tour'],
      guestOptions: ['1 Guest', '2 Guests'],
    },
    tours: {
      eyebrow: 'OUR TOURS',
      title: 'CHOOSE YOUR ADVENTURE',
      sub: 'Sea-Doo GTX PRO 130 jet ski tours — 4 hours across 10 islands',
      items: [
        {
          title: '10 ISLANDS · MORNING',
          desc: 'Fresh morning light, calm energy, and scenic photo stops across the route.',
          time: '4 Hours',
          guests: 'Up to 2',
          price: '฿7,500',
          features: [
            'Sea-Doo GTX PRO 130',
            'Professional guide',
            'Photo & rest stops',
            'Meal during the trip',
            'Free Phuket transfer',
          ],
          cta: 'VIEW TOUR DETAILS',
          popular: false,
        },
        {
          title: '10 ISLANDS · AFTERNOON',
          desc: 'Our most popular session — 4 hours, 10 islands, full support from start to finish.',
          time: '4 Hours',
          guests: 'Up to 2',
          price: '฿7,500',
          features: [
            'Sea-Doo GTX PRO 130',
            'Experienced guides',
            'Island scenery & nature',
            'Relax & photo breaks',
            'Care from arrival to end',
          ],
          cta: 'VIEW TOUR DETAILS',
          popular: true,
        },
        {
          title: 'PRIVATE TOUR',
          desc: 'A more private experience for couples or small groups who want flexible timing.',
          time: '4 Hours',
          guests: 'Up to 2 / ski',
          price: 'Ask Us',
          features: [
            'More flexible timing',
            'Closer guide support',
            'Great for first-timers',
            'Memorable photo moments',
            'Free hotel transfer',
          ],
          cta: 'PLAN PRIVATE TOUR',
          popular: false,
        },
      ],
    },
    why: {
      eyebrow: 'WHY RIDE WITH US',
      title: 'Built for thrill, guided with care',
      sub: 'Everything you need for a safe, exciting, and unforgettable sea day.',
      items: [
        {
          title: 'NEW JET SKIS',
          body: 'Ride Sea-Doo GTX PRO 130 for comfort and confident control.',
        },
        {
          title: 'LICENSED GUIDES',
          body: 'Local pros who know the route and keep the trip smooth.',
        },
        {
          title: 'SAFETY FIRST',
          body: 'Life jackets, briefing, and support across the full journey.',
        },
        {
          title: 'HOTEL TRANSFER',
          body: 'Complimentary round-trip pickup across Phuket.',
        },
      ],
    },
    video: {
      title: 'Island Hopping Like Never Before',
      body: 'Ride between islands and see Phuket from a whole new perspective.',
      cta: 'WATCH OUR VIDEO',
    },
    stops: {
      eyebrow: 'POPULAR STOPS',
      title: 'Highlights along the route',
      items: [
        {
          title: 'MONKEY ISLAND',
          desc: 'A fun nature stop for unforgettable photos',
          image: 'images/gallery-1.jpg',
        },
        {
          title: 'LIMESTONE BAY',
          desc: 'Turquoise water and lush cliff scenery',
          image: 'images/package-3.jpg',
        },
        {
          title: 'OPEN SEA RUN',
          desc: 'Open-water thrills with wide ocean views',
          image: 'images/hero.png',
        },
        {
          title: 'PHOTO STOP',
          desc: 'Pause, relax, and capture the moment',
          image: 'images/gallery-2.jpg',
        },
      ],
    },
    pricing: {
      eyebrow: 'TOUR PRICING',
      title: 'GREAT EXPERIENCES FOR EVERY TRAVELER',
      sub: 'Choose morning or afternoon — or ask us about a private session.',
      group: {
        title: 'STANDARD TOURS',
        from: 'From',
        price: '฿7,500',
        unit: 'per jet ski',
        features: [
          '4 hours · 10 islands',
          'Up to 2 guests per ski',
          'Guide throughout the trip',
          'Free Phuket transfer',
          'Meal during the tour',
        ],
        cta: 'VIEW STANDARD TOURS',
      },
      private: {
        title: 'PRIVATE TOURS',
        from: 'From',
        price: 'Ask Us',
        unit: 'custom arrangement',
        features: [
          'More flexible timing',
          'More private experience',
          'Ideal for couples & small groups',
          'Closer guide care',
          'Free hotel transfer',
        ],
        cta: 'PLAN PRIVATE TOUR',
      },
      note: 'Regular price ฿8,900 — book now for only ฿7,500 / jet ski',
    },
    reviews: {
      eyebrow: 'CUSTOMER REVIEWS',
      title: 'TRUSTED BY TRAVELERS',
      rating: '4.9',
      based: 'Based on traveler feedback from our tours',
      items: [
        {
          name: 'Anna K.',
          text: 'Amazing ride and beautiful views. The guides made everything feel easy and safe.',
        },
        {
          name: 'James R.',
          text: 'First time on a jet ski and I felt confident the whole way. Highly recommended.',
        },
        {
          name: 'Mei L.',
          text: 'Hotel transfer was so convenient. Great value with the current promo price.',
        },
      ],
    },
    gallery: {
      eyebrow: 'OUR GALLERY',
      title: 'REAL MOMENTS. REAL ADVENTURES.',
    },
    schedule: {
      morning: 'Morning Tour',
      morningTime: '9:00 AM – 1:00 PM',
      afternoon: 'Afternoon Tour',
      afternoonTime: '1:30 PM – 5:30 PM',
      note: 'Choose your preferred session when making a reservation',
    },
    contactPage: {
      eyebrow: 'CONTACT',
      title: 'Bookings & inquiries',
      companyTh: 'บริษัท จี.ไอ.ซี. วิสต้า จำกัด',
      formTitle: 'Send us a message',
      formDesc: 'Fill the form and continue the conversation on WhatsApp.',
      name: 'Name',
      message: 'Message',
      submit: 'Send via WhatsApp',
    },
    cta: {
      title: 'READY FOR YOUR PHUKET ADVENTURE?',
      body: 'Book the 4-hour, 10-island jet ski tour today — seats are limited each session.',
      whatsapp: 'Chat on WhatsApp',
      book: 'BOOK NOW',
      script: 'Good Vibes,\nBigger Adventures',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Frequently asked questions',
      items: [
        {
          q: 'How long is the tour and how many islands?',
          a: 'About 4 hours across up to 10 islands.',
        },
        {
          q: 'What times are available?',
          a: 'Morning 9:00 AM–1:00 PM and Afternoon 1:30–5:30 PM.',
        },
        {
          q: 'Is hotel transfer included?',
          a: 'Yes — complimentary round-trip transfer within Phuket.',
        },
        {
          q: 'Can beginners join?',
          a: 'Yes. Our team guides and supports you throughout the trip.',
        },
      ],
    },
    footer: {
      tagline: 'Jetski Travel & Sea Experience',
      quick: 'Quick Links',
      contact: 'Contact Us',
      follow: 'Follow Us',
      explore: 'EXPLORE · RIDE · DISCOVER PHUKET',
      rights: '© 2026 G.I. SEA VISTA CO., LTD. All rights reserved.',
      motto: 'Amazing People. Beautiful Places. Better Together.',
      company: 'G.I. SEA. VISTA CO., LTD.',
      address: '164 Moo 6, Paklok, Thalang, Phuket 83110',
    },
  },
} as const

export const contact = {
  phoneDisplay: '090 269 1898',
  phoneTel: '+66902691898',
  whatsapp: '66902691898',
  line: '@jetski.g.i',
  lineUrl: 'https://line.me/R/ti/p/@jetski.g.i',
  email: 'giseavista@gmail.com',
  facebook: 'Giseavista Jetskiphuket',
  telegram: '@jetski_6islands_phuket',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=164+Moo+6+Paklok+Thalang+Phuket+83110',
}
